package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Buildpack buildpack

swagger:model Buildpack
*/
type Buildpack struct {

	/* key
	 */
	Key string `json:"key,omitempty"`

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* url
	 */
	URL string `json:"url,omitempty"`
}

// Validate validates this buildpack
func (m *Buildpack) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
