package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*EnvironmentVariable environment variable

swagger:model EnvironmentVariable
*/
type EnvironmentVariable struct {

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* value
	 */
	Value string `json:"value,omitempty"`
}

// Validate validates this environment variable
func (m *EnvironmentVariable) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
