package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*ICMPInfo i c m p info

swagger:model ICMPInfo
*/
type ICMPInfo struct {

	/* code
	 */
	Code int64 `json:"code,omitempty"`

	/* type
	 */
	Type int64 `json:"type,omitempty"`
}

// Validate validates this i c m p info
func (m *ICMPInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
