package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*LifecycleData lifecycle data

swagger:model LifecycleData
*/
type LifecycleData struct {

	/* app bits download uri
	 */
	AppBitsDownloadURI string `json:"app_bits_download_uri,omitempty"`

	/* build artifacts cache download uri
	 */
	BuildArtifactsCacheDownloadURI string `json:"build_artifacts_cache_download_uri,omitempty"`

	/* build artifacts cache upload uri
	 */
	BuildArtifactsCacheUploadURI string `json:"build_artifacts_cache_upload_uri,omitempty"`

	/* buildpacks
	 */
	Buildpacks []*Buildpack `json:"buildpacks,omitempty"`

	/* droplet upload uri
	 */
	DropletUploadURI string `json:"droplet_upload_uri,omitempty"`

	/* stack
	 */
	Stack string `json:"stack,omitempty"`
}

// Validate validates this lifecycle data
func (m *LifecycleData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildpacks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LifecycleData) validateBuildpacks(formats strfmt.Registry) error {

	if swag.IsZero(m.Buildpacks) { // not required
		return nil
	}

	for i := 0; i < len(m.Buildpacks); i++ {

		if swag.IsZero(m.Buildpacks[i]) { // not required
			continue
		}

		if m.Buildpacks[i] != nil {

			if err := m.Buildpacks[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
