package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*StagingError staging error

swagger:model StagingError
*/
type StagingError struct {

	/* id
	 */
	ID string `json:"id,omitempty"`

	/* message
	 */
	Message string `json:"message,omitempty"`
}

// Validate validates this staging error
func (m *StagingError) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
