package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*TaskCallbackResponse task callback response

swagger:model TaskCallbackResponse
*/
type TaskCallbackResponse struct {

	/* annotation
	 */
	Annotation string `json:"annotation,omitempty"`

	/* created at
	 */
	CreatedAt int64 `json:"created_at,omitempty"`

	/* failed
	 */
	Failed bool `json:"failed,omitempty"`

	/* failure reason
	 */
	FailureReason string `json:"failure_reason,omitempty"`

	/* result
	 */
	Result string `json:"result,omitempty"`

	/* space
	 */
	Space string `json:"space,omitempty"`

	/* task guid
	 */
	TaskGUID string `json:"task_guid,omitempty"`
}

// Validate validates this task callback response
func (m *TaskCallbackResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
