package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cf-furnace/k8s-stager/lib/model"
)

// NewStagingCompleteParams creates a new StagingCompleteParams object
// with the default values initialized.
func NewStagingCompleteParams() StagingCompleteParams {
	var ()
	return StagingCompleteParams{}
}

// StagingCompleteParams contains all the bound params for the staging complete operation
// typically these are obtained from a http.Request
//
// swagger:parameters stagingComplete
type StagingCompleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: body
	*/
	StagingCompleteRequest *model.TaskCallbackResponse
	/*
	  Required: true
	  In: path
	*/
	StagingGUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *StagingCompleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body model.TaskCallbackResponse
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("stagingCompleteRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("stagingCompleteRequest", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.StagingCompleteRequest = &body
			}
		}

	} else {
		res = append(res, errors.Required("stagingCompleteRequest", "body"))
	}

	rStagingGUID, rhkStagingGUID, _ := route.Params.GetOK("staging_guid")
	if err := o.bindStagingGUID(rStagingGUID, rhkStagingGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StagingCompleteParams) bindStagingGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.StagingGUID = raw

	return nil
}
