package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cf-furnace/k8s-stager/lib/model"
)

/*StagingCompleteOK Status OK

swagger:response stagingCompleteOK
*/
type StagingCompleteOK struct {

	// In: body
	Payload *model.StagingResponseFromCC `json:"body,omitempty"`
}

// NewStagingCompleteOK creates StagingCompleteOK with default headers values
func NewStagingCompleteOK() *StagingCompleteOK {
	return &StagingCompleteOK{}
}

// WithPayload adds the payload to the staging complete o k response
func (o *StagingCompleteOK) WithPayload(payload *model.StagingResponseFromCC) *StagingCompleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the staging complete o k response
func (o *StagingCompleteOK) SetPayload(payload *model.StagingResponseFromCC) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StagingCompleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*StagingCompleteBadRequest Bad request

swagger:response stagingCompleteBadRequest
*/
type StagingCompleteBadRequest struct {
}

// NewStagingCompleteBadRequest creates StagingCompleteBadRequest with default headers values
func NewStagingCompleteBadRequest() *StagingCompleteBadRequest {
	return &StagingCompleteBadRequest{}
}

// WriteResponse to the client
func (o *StagingCompleteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*StagingCompleteNotFound Can't find staging task

swagger:response stagingCompleteNotFound
*/
type StagingCompleteNotFound struct {
}

// NewStagingCompleteNotFound creates StagingCompleteNotFound with default headers values
func NewStagingCompleteNotFound() *StagingCompleteNotFound {
	return &StagingCompleteNotFound{}
}

// WriteResponse to the client
func (o *StagingCompleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*StagingCompleteServiceUnavailable Cloud Controller unavailable

swagger:response stagingCompleteServiceUnavailable
*/
type StagingCompleteServiceUnavailable struct {
}

// NewStagingCompleteServiceUnavailable creates StagingCompleteServiceUnavailable with default headers values
func NewStagingCompleteServiceUnavailable() *StagingCompleteServiceUnavailable {
	return &StagingCompleteServiceUnavailable{}
}

// WriteResponse to the client
func (o *StagingCompleteServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}

/*StagingCompleteDefault Response code from Cloud Controller

swagger:response stagingCompleteDefault
*/
type StagingCompleteDefault struct {
	_statusCode int
}

// NewStagingCompleteDefault creates StagingCompleteDefault with default headers values
func NewStagingCompleteDefault(code int) *StagingCompleteDefault {
	if code <= 0 {
		code = 500
	}

	return &StagingCompleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the staging complete default response
func (o *StagingCompleteDefault) WithStatusCode(code int) *StagingCompleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the staging complete default response
func (o *StagingCompleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *StagingCompleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
}
