package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStopStagingParams creates a new StopStagingParams object
// with the default values initialized.
func NewStopStagingParams() StopStagingParams {
	var ()
	return StopStagingParams{}
}

// StopStagingParams contains all the bound params for the stop staging operation
// typically these are obtained from a http.Request
//
// swagger:parameters stopStaging
type StopStagingParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	StagingGUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *StopStagingParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rStagingGUID, rhkStagingGUID, _ := route.Params.GetOK("staging_guid")
	if err := o.bindStagingGUID(rStagingGUID, rhkStagingGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopStagingParams) bindStagingGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.StagingGUID = raw

	return nil
}
