package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*StopStagingAccepted Request to stop accepted

swagger:response stopStagingAccepted
*/
type StopStagingAccepted struct {
}

// NewStopStagingAccepted creates StopStagingAccepted with default headers values
func NewStopStagingAccepted() *StopStagingAccepted {
	return &StopStagingAccepted{}
}

// WriteResponse to the client
func (o *StopStagingAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
}

/*StopStagingNotFound Staging task not found

swagger:response stopStagingNotFound
*/
type StopStagingNotFound struct {
}

// NewStopStagingNotFound creates StopStagingNotFound with default headers values
func NewStopStagingNotFound() *StopStagingNotFound {
	return &StopStagingNotFound{}
}

// WriteResponse to the client
func (o *StopStagingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*StopStagingInternalServerError Internal error

swagger:response stopStagingInternalServerError
*/
type StopStagingInternalServerError struct {
}

// NewStopStagingInternalServerError creates StopStagingInternalServerError with default headers values
func NewStopStagingInternalServerError() *StopStagingInternalServerError {
	return &StopStagingInternalServerError{}
}

// WriteResponse to the client
func (o *StopStagingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
